server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri.html $uri/ =404;
  }

  location ~* \.(?:css|svg|xml|txt|png|jpg|jpeg|webp|ico)$ {
    try_files $uri =404;
    expires 1h;
    add_header Cache-Control "public";
  }
}
